### ISSUE TITLE
(setq t nil)

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#168]
Generates the wrong error - I think it's a typo in sicl/Code/Cleavir/Generate-AST/convert-special.lisp line 563  - I sent this to beach

**Comment by Bike** [comment]
The current error seems to be `CLEAVIR-GENERATE-AST::SETQ-CONSTANT VARIABLE` with the explanatory text "The variable assigned to in a SETQ must not be a constant variable, but the following constant variable was found: T" which sounds good to me.

This was probably fixed by https://github.com/robert-strandh/SICL/commit/7b8877390dedec80d56c8c178492578b6775755c

**Comment by Shinmera** [comment]
Can confirm fixed on 1b63a29f869513c9fec111b5963d98aa0503155b
