### ISSUE TITLE
What do you want from Clasp?

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#18]
I'll start:

1) Compiler that generates faster code. 
2) Documentation.
3) Stability - fewer segfaults
4) Demos for exposing C++ to Clasp Common Lisp.
5) Expose interesting libraries to Clasp: numerical methods, Qt (UI library) etc

**Comment by benwbooth** [comment]
```Leverage C++ as easy as Clojure leverages Java```

I wonder what would be required to make that happen. In clojure, no extra clbind-like descriptors are necessary because of Java reflection. The only way I can think of to get this functionality would be to either add reflection to C++ (with Qt MOC or maybe libclang-based AST parsing of header files), or to write a dialect of common lisp that compiles directly to C++ code. That way, you could call C++ directly from the CL source. But you'd still have to somehow automatically handle type conversions of arguments and return values.

Still, it would be great if clasp could do this, instead of requiring writing clbind descriptors to import C++ symbols into CL.

**Comment by benwbooth** [comment]
Another useful feature would be the ability to embed C/C++ directly into clasp with special syntax. This is what [Ferret](http://nakkaya.com/2011/06/29/ferret-an-experimental-clojure-compiler/#sec-3-2) can do:

```
(defn video-capture [i]
  #<
  cv::VideoCapture *cap = new cv::VideoCapture(NUMBER(i)->intValue());
  if (cap->isOpened())
   __result = var(new Pointer(cap));
  >#)
```

Not sure how difficult this would be to implement, but it would make interfacing with C++ much easier than having to list every imported symbol with clbind.

**Comment by GOFAI** [comment]
Do you plan for Clasp to provide tail call optimization? I'm currently getting segfaults from some recursive functions...

**Comment by Shinmera** [comment]
Individual features should get individual issue tickets.
