### ISSUE TITLE
Annotate C++ Functions That Are Exposed as a CL Function and develop a new scraper in CL

### ISSUE THREAD

**Issue by Shinmera** [drmeister/clasp#182]
Currently when reading the source code it is hard to impossible to know whether a given C++ function or method signifies one that is exposed as a CL function. Additionally, these functions need to be manually linked into the CL space, and there is currently no support for Slime/Emacs to be able to jump to the correct definition when looking it up.

In order to fix this, a form of annotation mechanism should be employed that has two primary purposes, the first of which is to serve as a clear hint to the reader that this is a function that will be exposed to CL, and the second being that it should automatically handle the linkup into the CL side in order to avoid having to duplicate this information in additional files.

The current suggested path for adding such an annotation is through a custom scraper step in the build process, as well as a C++ macro in the form of a `#define` or `#pragma` directive that can be prepended to function definitions. This should be the most intuitive and readable option while still being reasonably doable with current toolchains.

**Comment by Shinmera** [comment]
@Georgiy-Tugai @drmeister Please document the more specific details of the proposed solutions in this issue ticket.

**Comment by drmeister** [comment]
To expose C++ functions the following approach could be taken.

Declare a cpp macro:
    #ifdef SCRAPER_ACTIVE
        #define CL_DEFUN(pkg_name,lambdalist,decl,docstring) CL_DEFUN482348532BEGIN pkg_name lambdalist CL_DEFUN3428342835234END
    #else
       #define CL_DEFUN(pkg_name,lambdalist,decl,docstring)
    #endif

In the code use:
    CL_DEFUN(*,(a b &optional c),,)
    int foo(int a, int b, int c=0) {
    ...
    };

**Comment by drmeister** [comment]
flash- made a very good point.  What languages are the programmers who look at this going to know?   Common Lisp and C++.   We should write this in Common Lisp and not Perl or C++.

We can do it in vanilla Common Lisp because the C-preprocessor will do the heavy lifting.

**Comment by Georgiy-Tugai** [comment]
When you say "vanilla Common Lisp", do you mean a 3rd-party implementation, bclasp, or something else? Furthermore, do you mean that we cannot use Quicklisp (or other) libraries in this scraper?

**Comment by drmeister** [comment]
I was thinking SBCL or ECL.  We could use quicklisp if necessary, but it brings in other dependencies.

**Comment by drmeister** [comment]
To get started I would say we parse the output of bjam and for each compilation command line insert -E into the command line and substitute .i for .o in each command line.  We can check if the .i file is newer or older than the input source file and only run the preprocessor on the newer source files.   Then we open each preprocessed file and search for tags.  Also SAL9000 suggested opening the original source file and advancing to the line numbers provided by the preprocessed file to find the byte offset of each CL_DEFUN.  The source file name and byte offset would be written into a separate file to be read by either the C++ source code or the CL source code to allow M-. to jump to C++ source.

**Comment by drmeister** [comment]
In the symbol scraper and class scraper (I called the grovelers and they are run by the clasp/src/common/build script)  I write the C++ output into a string-stream.  Then I load the current C++ output into another string and just compare the strings.  Only if they don't match do I write the new C++ output into the file. We should do the same thing for the four files that the new scraper will generate.   It will generate:
1. A symbol initialization file
2. A class initialization file
3. A function/method? initialization file.
4. A source position file.

**Comment by drmeister** [comment]
I went ahead and just wrote the new scraper.  I know we started out discussing it like SAL9000 and I would write it but it ties so intimately into Clasp and I learned so many lessons from writing scrapers for C++ over the years.    SAL9000's suggestion to run the code through the C-preprocessor was brilliant though - it solves so many problems.

It guarantees the format of the input.  It allows us to comment out tags using #if 0/#endif /* ... */ // 

Scraping this way will add some time to the build.  It takes about 30 seconds to read all of the preprocessed files. There may be inefficiencies in the code - although I tried hard to avoid them.

I load entire preprocessed files into memory in one go and then search the file for tags.

It takes about 4 minutes to preprocess all of the source files. But the scraper only preprocesses missing files and files that need to be updated.   You run bjam twice to generate input files for the scraper.  Once with "-n -a" to generate all compile commands and again with just "-n" to generate just compile commands for preprocessed files that need to be rebuilt because some dependency changed.

The code is in clasp/src/scraper

**Comment by Shinmera** [comment]
Has the system been fully moved over to this, or are there any functions left to annotate?

**Comment by drmeister** [comment]
The system has been fully moved over to this for months.  Everything seems to be working swimmingly.  
There is no CXX_NAMESPACE tag - it wasn't necessary.

**Comment by Shinmera** [comment]
Closing accordingly then.

**Comment by drmeister** [comment]
This is the same as issue #234
