### ISSUE TITLE
submodule error

### ISSUE THREAD

**Issue by dunn** [drmeister/clasp#356]
When doing a fresh recursive clone, I get this error on the SICL submodule:
```
error: Server does not allow request for unadvertised object 8f637326f8b1a2cec32e65e81bdb3e435e3b6dc3
Fetched in submodule path 'src/lisp/kernel/contrib/sicl', but it did not contain 8f637326f8b1a2cec32e65e81bdb3e435e3b6dc3. Direct fetching of that commit failed.
```

**Comment by Shinmera** [comment]
I assume you're cloning the master branch, which is woefully outdated. Use `testing` instead.

**Comment by dunn** [comment]
So I was!  I saw that it got some recent updates, so I assumed development had switched back over.

**Comment by Bike** [comment]
meister updated master a few days ago, so it's just regular outdated instead of years-ago outdated. So this should work, hypothetically.

I believe the problem is that the SICL submodule is done with a lot of rebasing; the commit it's trying for was the latest a few weeks ago, but got erased by later rebasing. I would be interested to know if there is any way to fix this besides the obvious "don't rebase". (Not that I wouldn't like to stop.)
