### ISSUE TITLE
COMPILE given an interpreted closure signals an error

### ISSUE THREAD

**Issue by kpoeck** [drmeister/clasp#379]
Just happens with slime, not in a shell  all clasp directly
 (defun foo (n)(if (<= n 1) 1 (* n (foo (1- n)))))
 (compile 'foo)
->
The symbol COMPILER::FUNCTION-DOCSTRING has no function bound to it
   [Condition of type CORE:SIMPLE-PROGRAM-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.

Backtrace:
  0: SIGNAL-SIMPLE-ERROR
  1: GENERATE-LAMBDA-EXPRESSION-FROM-INTERPRETED-FUNCTION
  2: COMPILE
  3: (LAMBDA)
  4: (EVAL-REGION "(compile 'foo)\n")

Looking at the sources:
in codegen.lisp
```
(defun generate-lambda-expression-from-interpreted-function (fn)
  (let* ((lambda-list-handler (function-lambda-list-handler fn))
	 (lambda-list (lambda-list-handler-lambda-list lambda-list-handler))
	 (declares (function-declares fn))
	 (docstring (function-docstring fn))
```
....

but compiler::function-docstring does not seem to be defined in the image

**Comment by Bike** [comment]
The function is just `docstring`. Dunno why it's wrong, I can fix it in a bit.

**Comment by Bike** [comment]
That commit should fix it.

To be clear on the etiology, this has to do with slime only indirectly. The actual problem is that the long-underexercised path in `cl:compile` for taking an interpreted closure and getting a compiled function out of it was missing a few things. You noticed it in Slime because of how special variables (specifically, `core:*use-interpreter-for-eval*`) in threads work.

@kpoeck would you kindly pull dev and try this again?

**Comment by kpoeck** [comment]
Works now fin in dev compiled yesterday
