### ISSUE TITLE
Ansi-tests: elt on array segfaults with incorrect arguments

### ISSUE THREAD

**Issue by kpoeck** [drmeister/clasp#395]
Test  elt.error.4
Simplified

COMMON-LISP-USER> (elt #(1 2 3) -1)
Segmentation fault: 11

(elt (vector 1 2 3 4 5) -1)
#<VA-LIST: Segmentation fault: 11

**Comment by Bike** [comment]
`elt` is currently defined [here](https://github.com/drmeister/clasp/blob/master/src/core/sequence.cc#L146) as calling an elt method on conses, type-erroring on nil, and the underlying row-major-aref on vectors.

The behavior on nil is wrong, it signals an error that nil is not of type sequence, which is false. I'm not sure what's going on with rowMajorAref, since we don't actually use that method for `cl:row-major-aref` in the finished clasp now. I'll probably just do the same thing, defining `elt` in inline.lisp like `length` already is.

**Comment by kpoeck** [comment]
Now returns a nice simple-error, fixed in dev, so closing
