### ISSUE TITLE
Ironclad MD5 digest doesn't appear to generate correct results.

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#399]
Compare these results:

```
(let ((*print-base* 16)
      (*print-pretty* nil))
  (format t "My md5      : ~a~%" (coerce (core:digest-md5 (list (core:make-simple-vector-byte8-from-base-string "a"))) 'simple-vector))
  (format t "Ironclad md5: ~a~%" (coerce (let ((digester (ironclad:make-digest :md5)))
                                           (ironclad:update-digest digester (core:make-simple-vector-byte8-from-base-string "a"))
                                           (ironclad:produce-digest digester)) 'simple-vector)))
```

`My md5      : #(C C1 75 B9 C0 F1 B6 A8 31 C3 99 E2 69 77 26 61)`
`Ironclad md5: #(D3 F7 97 93 32 E6 E1 B7 75 DD 70 75 3F 20 17 77)`

To http://www.sha1-online.com
`0cc175b9c0f1b6a831c399e269772661`

**Comment by Bike** [comment]
Better:
```
(core::fill-array-with-seq (core:make-vector 'ext:byte32 4)
                          '(4149444226 3174756917 718787259 3951481745))
=> #(1258104430 1258104438 718787259 1258104446)
```

**Comment by Bike** [comment]
the commit message has more detail, but to summarize, ironclad has an vector of `(unsigned-byte 32)` for the constant array `K` used by the md5 algorithm. clasp computed double floats which, due to an error, resulted in positive bignums smaller than 2^62 (i.e. in the fixnum range) when truncated. It then stored these in the vector. The inlined vector storage code treats the argument as a fixnum regardless of whether it is one, on the assumption that any number of the correct size is a fixnum - an assumption that's fine, we just broke it by accident.

The fix was to ensure that bignums inside the fixnum range are not created by conversion from floating point. The hashes match for me now.
