### ISSUE TITLE
Parallelizing the lisp part of the build would make things run faster

### ISSUE THREAD

**Issue by fmitha** [drmeister/clasp#43]
Tthe lisp part of the build seems to run sequentially on one core. Parallelizing this would speed things up considerably. I'm don't know how difficult this would be to do, though.

**Comment by Shinmera** [comment]
Parallelising lisp builds is notoriously difficult due to the various side effects that may occur in each stage of the compilation, essentially forcing each compilation to have every dependant file `load`ed beforehand. I might work on a build system that tries to still work with these constraints at some point, but due to bootstrapping issues it is highly unlikely that it will ever be used for Clasp, except for the case of rebuilding itself or using an external implementation.

For the moment, I deem this such a difficult task that I'll close it with WontFix.
